build: false
shallow_clone: false
skip_branch_with_pr: true
clone_depth: 1

environment:

  matrix:
    - python: "C:/Python38-x64"
    - python: "C:/Python36-x64"
    - python: "C:/Python35"

cache:
  - C:\Users\appveyor\AppData\Local\pip\Cache

init:
  - cmd: set PATH=%python%;%python%\scripts;%PATH%

install:
  - cmd: |
        python -m pip install --upgrade setuptools pip wheel
        pip --version
  - cmd: |
        pip install --pre -e .
        pip install ipykernel[test]
  - cmd: |
        pip install matplotlib numpy
        pip freeze
  - cmd: python -c "import ipykernel.kernelspec; ipykernel.kernelspec.install(user=True)"

test_script:
  - cmd: pytest -v -x --cov ipykernel ipykernel

on_success:
  - cmd: pip install codecov
  - cmd: codecov
